---
language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm install -g jshint@^2.6.3"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - jshint .
  - npm test

notifications:
    email: false
matrix:
    fast_finish: true
    allow_failures:
        - node_js: "iojs"
